<?php

/**
 * @file
 * Implements Drupal hooks for stanford_earth_r25 module.
 */

/**
 * Hook to format emailed error messages to site admin.
 *
 * @param string $key
 *   The type of email being sent.
 * @param array $message
 *   The message array that can be modified by this hook.
 * @param array $params
 *   The parameter array whose contents can be used to format the message.
 */
function stanford_earth_r25_mail($key, array &$message, array $params) {
  switch ($key) {
    case 'r25_error':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('R25 API error: @title', ['@title' => $params['r25']]);
      $message['body'][] = $params['message'];
      break;
  }
}

function stanford_earth_r25_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'stanford_earth_r25-theme-hook' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'stanford_earth_r25-theme-hook',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'r25_location' => NULL,
        'photo_url' => '',
      ],
    ],
  ];

}
