<?php

/**
 * @file
 * Implements Drupal hooks for stanford_earth_r25 module.
 */

/**
 * Hook to format emailed error messages to site admin.
 *
 * @param string $key
 *   The type of email being sent.
 * @param array $message
 *   The message array that can be modified by this hook.
 * @param array $params
 *   The parameter array whose contents can be used to format the message.
 */
function stanford_earth_r25_mail($key, array &$message, array $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  $body = '';
  if (!empty($params['message']) && is_array($params['message'])) {
    foreach ($params['message'] as $msgline) {
      $body .= $msgline . '<br />';
    }
  }
  switch ($key) {
    case 'r25_operation':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@operation', array('@operation' => $params['r25_operation']), $options);
      $message['body'][] = $body;
      break;
    case 'r25_error':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('R25 API error: @title', ['@title' => $params['r25']]);
      $message['body'][] = $body;
      break;
  }
}

/**
 * Hook to establish twig template for module.
 *
 * @param array $existing
 *   Array of existing implementations.
 * @param string $type
 *   How the theme is being implemented.
 * @param string $theme
 *   The name of the theme being implemented.
 * @param string $path
 *   The directory path of the module.
 * @return array
 *   Theme template information.
 */
function stanford_earth_r25_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'stanford_earth_r25-theme-hook' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'stanford_earth_r25-theme-hook',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'r25_location' => NULL,
        'photo_url' => '',
        'form' => NULL,
        'canBook' => FALSE,
      ],
    ],
  ];

}
