<?php

/**
 * @file
 * Reservation form customizations for Hartley, Press Building, and Farm.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\stanford_earth_r25\StanfordEarthR25Util;
use Drupal\stanford_earth_r25\Entity\StanfordEarthR25Location;
use Drupal\Core\Url;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Routing\TrustedRedirectResponse;
use GuzzleHttp\Exception\GuzzleException;

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_is_sdss_user() {
  if (!empty(array_intersect(
    Drupal::currentUser()->getRoles(), ['custm_sdss_user', 'administrator']))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_get_phone_number() {
  $uid = \Drupal::service('externalauth.authmap')
    ->get(Drupal::currentUser()->id(), 'samlauth');
  $phone_number = '';
  if (!empty($uid)) {
    $access_token = '';
    $token = Drupal::cache()->get("cap:access_token");
    if (!empty($token)) {
      $access_token = $token->data['access_token'];
    }
    else {
      $config_pages = \Drupal::service('config_pages.loader');
      $capid = $config_pages->getValue('stanford_person_importer', 'su_person_cap_username', 0, 'value') ?? '';
      $capsecret = $config_pages->getValue('stanford_person_importer', 'su_person_cap_password', 0, 'value') ?? '';
      if (!empty($capid) && !empty($capsecret)) {
        $query = ['query' => ['grant_type' => 'client_credentials']];
        $auth_url = Url::fromUri('https://authz.stanford.edu/oauth/token', $query);
        $response = NULL;
        $options = ['auth' => [$capid, $capsecret]];
        try {
          $response = Drupal::httpClient()
            ->request('GET', $auth_url->toString(TRUE)
              ->getGeneratedUrl(), $options);
        }
        catch (GuzzleException | \Exception $e) {
          Drupal::cache()->delete('cap:access_token');
          // Most errors originate from the API itself, log and fail over.
          Drupal::logger('stanford_earth_r25')
            ->error('An unexpected error came from the API: %message', ['%message' => $e->getMessage()]);
        }
        $token = FALSE;
        if (!empty($response) && $response->getStatusCode() == 200) {
          $token = json_decode($response->getBody(), TRUE, 512);
        }
        if (!empty($token)) {
          Drupal::logger('stanford_earth_r25')->info('new access token written to cache');
          Drupal::cache()->set('cap:access_token', $token,
            time() + $token['expires_in'] - 3600,
            ['stanford_earth_r25']);
          $access_token = $token['access_token'];
        }
      }
    }
    if (!empty($access_token)) {
      $query = [
        'uids' => $uid,
        'access_token' => $access_token,
      ];
      $options = ['query' => $query];
      $url = Url::fromUri('https://cap.stanford.edu/cap-api/api/profiles/v1', $options);
      $response = Drupal::httpClient()->request('GET', $url->toString(TRUE)
        ->getGeneratedUrl());
      $data = json_decode($response->getBody(), TRUE, 512);
      if (!empty($data['values'][0]['primaryContact']['phoneNumbers'][0])) {
        $phone_number = $data['values'][0]['primaryContact']['phoneNumbers'][0];
      }
    }
  }
  return $phone_number;
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_is_room_category($form, $category = '') {
  if (!empty($category) && !empty($form['stanford_r25_booking_rules_category']['#value'])) {
    if ($category === $form['stanford_r25_booking_rules_category']['#value']) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_is_room_admin($form) {
  $isAdmin = FALSE;
  if (!empty($form['stanford_r25_booking_roomid']['#value'])) {
    $location = StanfordEarthR25Location::load($form['stanford_r25_booking_roomid']['#value']);
    if (!empty($location->get('room_administrator_roles')) &&
      !empty(array_intersect(Drupal::currentUser()->getRoles(),
        $location->get('room_administrator_roles')))) {
      $isAdmin = TRUE;
    }
  }
  return $isAdmin;
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id,
) {
  if ($form_id === 'stanford_earth_r25_reservation') {
    $room_admin = stanford_earth_hartley_is_room_admin($form);
    $hartley_room = stanford_earth_hartley_is_room_category($form, 'hartley');
    $press_building_room = stanford_earth_hartley_is_room_category($form, 'press_building');
    $farm_room = stanford_earth_hartley_is_room_category($form, 'farm');
    if ($farm_room) {
      $form['stanford_r25_booking_headcount']['#title'] = t('Headcount');
      $event_code = $form['#attached']['drupalSettings']['stanfordEarthR25']['stanfordR25Room']['override_event_code'] ?? 0;
      if ($event_code !== '526') {
        $form['stanford_r25_booking_headcount']['#max'] = "40";
      }
    }
    if ($hartley_room || $press_building_room || $farm_room) {
      if ($press_building_room) {
        if (!empty($form['#attached']['drupalSettings']['stanfordEarthR25']['stanfordR25Room']['post_process_redirect_url'])) {
          $press_user = $room_admin ||
            !empty(array_intersect(Drupal::currentUser()->getRoles(),
              ['custm_press_building_user', 'custm_press_building_admin']));
          if (!$press_user) {
            $form['#attached']['drupalSettings']['stanfordEarthR25']['pressRedirect'] = TRUE;
            if (!empty($form['stanford_r25_booking_roomid']['#value']) &&
              $form['stanford_r25_booking_roomid']['#value'] === 'sa03') {
              $markup = strval($form['r25_instructions']['#markup']);
              $markup = str_replace("<p>Reservations", "<p>Meeting reservations", $markup);
              $markup = str_replace("For questions", "For the Event Space, you will be redirected to a detailed request form after clicking Reserve below. For questions", $markup);
              $form['r25_instructions']['#markup'] = $markup;
            }
          }
        }
      }
      if (empty($form['#validate'])) {
        $form['#validate'] = [];
      }
      $form['#validate'][] = 'stanford_earth_hartley_form_validate';
      if (empty($form['#submit'])) {
        $form['#submit'] = [];
      }
      $form['#submit'][] = 'stanford_earth_hartley_form_submit';
      if (!empty($form['stanford_r25_booking_attr176']['#title'])) {
        $form['stanford_r25_booking_attr176']['#title'] = 'Is the event host using this space for the first time?';
        $form['stanford_r25_booking_attr176']['#description'] = 'If so, we will be in touch with additional instructions after your reservation is confirmed.';
      }
      if (!empty($form['stanford_r25_booking_attr169']['#title']) &&
        !empty($form['stanford_r25_booking_attr170']['#title'])) {
        $form['stanford_r25_booking_attr169']['#title'] = 'Will food and/or beverages be served at this event?';
        $form['stanford_r25_booking_attr169']['#description'] = 'If so, you must acknowledge that a work order for cleanup ' .
          'is required and must be received by the Stanford Doerr School of Sustainability no less than 48 ' .
          'hours before the event.';
        $form['stanford_r25_booking_attr170']['#title'] = 'I agree to provide a work order for after-event cleanup.';
        $form['stanford_r25_booking_attr170']['#states'] = [
          'required' => [
            ':input[name="stanford_r25_booking_attr169"]' => [
              'checked' => TRUE,
            ],
          ],
          'visible' => [
            ':input[name="stanford_r25_booking_attr169"]' => [
              'checked' => TRUE,
            ],
          ],
        ];
      }
      if (!empty($form['stanford_r25_booking_attr171']['#title'])) {
        if ($room_admin && !$farm_room) {
          $form['stanford_r25_booking_attr171']['#type'] = 'hidden';
        }
        else {
          $form['stanford_r25_booking_attr171']['#type'] = 'markup';
          $form['stanford_r25_booking_attr171']['#markup'] = '<br/><strong>Please provide a PTA number and Sponsoring Department.</strong><br/>';
        }
      }
      if (!empty($form['stanford_r25_booking_attr172']['#title'])) {
        if ($room_admin && !$farm_room) {
          $form['stanford_r25_booking_attr172']['#type'] = 'hidden';
        }
        else {
          $form['stanford_r25_booking_attr172']['#title'] = 'University PTA number';
          $form['stanford_r25_booking_attr172']['#description'] = 'PTA format is 1234567-1-ABCDE.';
          if (!$room_admin) {
            $form['stanford_r25_booking_attr172']['#required'] = TRUE;
          }
        }
      }
      if (!empty($form['stanford_r25_booking_attr173']['#title'])) {
        if ($room_admin && !$farm_room) {
          $form['stanford_r25_booking_attr173']['#type'] = 'hidden';
        }
        else {
          $form['stanford_r25_booking_attr173']['#title'] = 'Sponsoring Department';
          $form['stanford_r25_booking_attr173']['#description'] = 'Which school department sponsors this PTA?';
          if (!$room_admin) {
            $form['stanford_r25_booking_attr173']['#required'] = TRUE;
          }
        }
      }
      $press_redirect = !empty($form['#attached']['drupalSettings']['stanfordEarthR25']['pressRedirect']);
      if (!empty($form['stanford_r25_booking_attr177']['#title'])) {
        $form['stanford_r25_booking_attr177']['#title'] = 'Description/Comments';
        $form['stanford_r25_booking_attr177']['#description'] = 'Any information, questions or remarks about this reservation.';
        if ($press_building_room) {
          $form['stanford_r25_booking_attr177']['#visible'] = FALSE;
          if (!$press_redirect) {
            $form['stanford_r25_booking_attr177']['#states'] = [
              'required' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => '2605',
                ],
              ],
              'visible' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => '2605',
                ],
              ],
            ];
          }
          else {
            $form['stanford_r25_booking_attr177']['#states'] = [
              'required' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => 'XXXX',
                ],
              ],
              'visible' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => 'XXXX',
                ],
              ],
            ];
          }
        }
        else {
          $form['stanford_r25_booking_attr177']['#visible'] = TRUE;
          $form['stanford_r25_booking_attr177']['#required'] = TRUE;
        }
      }
      if (!empty($form['stanford_r25_contact_175']['#title'])) {
        $phone_number = stanford_earth_hartley_get_phone_number();
        if (!empty($phone_number)) {
          $form['stanford_r25_contact_175']['#default_value'] .= $phone_number . "\r\n";
          $form['stanford_r25_contact_175']['#description'] = 'Please make sure we have your correct contact information including email address and phone number';
        }
        $form['stanford_r25_contact_175']['#title'] = 'Event Contact Info';
        $form['stanford_r25_contact_175']['#visible'] = FALSE;
        if ($press_building_room) {
          if (!$press_redirect) {
            $form['stanford_r25_contact_175']['#states'] = [
              'required' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => '2605',
                ],
              ],
              'visible' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => '2605',
                ],
              ],
            ];
          }
          else {
            $form['stanford_r25_contact_175']['#states'] = [
              'required' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => 'XXXX',
                ],
              ],
              'visible' => [
                ':input[name="stanford_r25_booking_spaceid"]' => [
                  'value' => 'XXXX',
                ],
              ],
            ];
          }
        }
        else {
          $form['stanford_r25_contact_175']['#visible'] = TRUE;
          $form['stanford_r25_contact_175']['#required'] = TRUE;
        }
      }
      if (!empty($form['stanford_r25_booking_attr311']['#title'])) {
        $form['stanford_r25_booking_attr311']['#title'] = 'Food Allergies/Preferences';
        $form['stanford_r25_booking_attr311']['#description'] = 'Please list any food allergies or preferences for your attendees.';
      }
      if (!empty($form['stanford_r25_booking_attr312']['#title'])) {
        $storage = $form_state->getStorage();
        if (!empty($storage['stanford_earth_r25']['price'])) {
          $price = $storage['stanford_earth_r25']['price'];
          $form['stanford_r25_booking_attr312']['#value'] = $price;
          unset($storage['stanford_earth_r25']['price']);
          $form_state->setStorage($storage);
        }
        $form['stanford_r25_booking_attr312']['#type'] = 'hidden';
      }
      $form['#attached']['library'][] = 'stanford_earth_hartley/stanford_earth_hartley';
    }
  }
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_form_validate(&$form, FormStateInterface $form_state) {
  $room_admin = stanford_earth_hartley_is_room_admin($form);
  $hartley_room = stanford_earth_hartley_is_room_category($form, 'hartley');
  $farm_room = stanford_earth_hartley_is_room_category($form, 'farm');
  $press_building_room = stanford_earth_hartley_is_room_category($form, 'press_building');
  if (($hartley_room || $farm_room || $press_building_room) && !$room_admin) {
    // Make sure there is a PTA number and sponsoring department.
    if (!empty($form['stanford_r25_booking_attr172']['#title'])) {
      if (empty($form_state->getValue('stanford_r25_booking_attr172'))) {
        $form_state->setErrorByName('stanford_r25_booking_attr172',
          'Please provide a PTA number for billing for this reservation.');
        return;
      }
      else {
        // Check if the PTA number is in the correct format.
        $pta_str = $form_state->getValue('stanford_r25_booking_attr172');
        $results = [];
        $pattern = "/^[\d]{7,7}-[\d][\d\.]{0,7}-[A-Z]{5,5}$/";
        if (preg_match($pattern, $pta_str, $results) != 1) {
          $form_state->setErrorByName('stanford_r25_booking_attr172',
            'Please provide a PTA number in its proper format.');
          return;
        }
      }
    }
    if (!empty($form['stanford_r25_booking_attr173']['#title'])) {
      if (empty($form_state->getValue('stanford_r25_booking_attr173'))) {
        $form_state->setErrorByName('stanford_r25_booking_attr173',
          'Please provide a sponsoring department or signature authority name for billing for this reservation.');
        return;
      }
    }
    if (!empty($form['stanford_r25_booking_attr175']['#title'])) {
      if (empty(trim($form_state->getValue('stanford_r25_contact_175')))) {
        $form_state->setErrorByName('stanford_r25_contact_175',
          'Please enter your contact information in the provided field.');
        return;
      }
    }
    if (!empty($form['stanford_r25_booking_attr169']['#title'])) {
      if (!empty($form_state->getValue('stanford_r25_booking_attr169')) &&
        intval($form_state->getValue('stanford_r25_booking_attr169')) == 1) {
        if (empty($form_state->getValue('stanford_r25_booking_attr170')) ||
          intval($form_state->getValue('stanford_r25_booking_attr170') == 0)) {
          $form_state->setErrorByName('stanford_r25_booking_attr170',
            'If you are serving food or beverages, you must agree to provide a work order for cleanup.');
          return;
        }
      }
    }
    // For Hartley, make sure the requested dates are in the accepted range.
    if ($hartley_room) {
      $month = intval(date('n'));
      $year = intval(date('Y'));
      $start_year = intval($form_state->getValue('stanford_r25_booking_date')
        ->format('Y'));
      $end_year = intval($form_state->getValue('stanford_r25_booking_enddate')
        ->format('Y'));
      if ($month < 10 && ($start_year != $year || $end_year != $year)) {
        $form_state->setErrorByName('stanford_r25_booking_date',
          'You may only reserve this space for dates during the current year.');
        return;
      }
      else {
        if ($start_year > $year + 1 || $end_year > $year + 1) {
          $form_state->setErrorByName('stanford_r25_booking_date',
            'You may only reserve this space for dates during the remainder of this year and next year.');
          return;
        }
      }
    }
  }
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_form_submit(&$form, FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  if (!empty($storage['stanford_earth_r25']['stanford_r25_postprocess'])) {
    $storage = $storage['stanford_earth_r25']['stanford_r25_postprocess'];
    $room = $storage['room'];
    $dates = $storage['dates'];
    $space_str = $room['label'];
    $space_id = '';
    if (str_contains($room['space_id'], '+')) {
      $space_id = $form_state->getValue('stanford_r25_booking_spaceid');
      $space_str = $form['stanford_r25_booking_spaceid']['#options'][$space_id];
    }
    if (!empty($storage['mailto'])) {
      $hartley_room = stanford_earth_hartley_is_room_category($form, 'hartley');
      $press_building_room = stanford_earth_hartley_is_room_category($form, 'press_building');
      $farm_room = stanford_earth_hartley_is_room_category($form, 'farm');
      $mail_list = $storage['mailto'];
      $subject = $room['label'] . ': Your booking request is now pending approval';
      $body = [];
      $body[] = 'The booking manager will review and approve your request as soon as possible, and will contact you if there is a problem.';
      $body[] = 'The details of your booking request follow.';
      $body[] = 'Event name: ' . $storage['event_name'];
      if ($hartley_room) {
        if ($space_id == '1675') {
          $space_str .= ' (Does *not* include Mitchell Patio)';
        }
        else {
          if ($space_id == '1860') {
            $space_str .= ' (Does *not* include Hartley Conference Room and Kitchen';
          }
        }
      }
      $body[] = 'Event space: ' . $space_str;
      $body[] = 'Starting: ' . DateTime::createFromFormat(DATE_W3C, $dates['start'])->format("l, F j, Y g:i a");
      $body[] = 'Ending: ' . DateTime::createFromFormat(DATE_W3C, $dates['end'])->format("l, F j, Y g:i a");
      $est_fee = $storage['est_charge'];
      if ($est_fee > 0) {
        $body[] = 'Estimated Room Fee: $' . $est_fee . ' --reflects fee scheduled for time of event. Fees subject to change.';
      }
      if ($hartley_room) {
        $body[] = 'If food IS served or consumed, you must get a work order from Custodial Services. This is not negotiable. ';
        $body[] = 'Allow at least 30 minutes for cleanup if you get a work order.';
      }
      $emailAddr = '';
      if (($hartley_room || $farm_room || $press_building_room) &&
        !empty($room['room_administrator_emails'])) {
        $emailAddr = 'mailto:' . $room['room_administrator_emails'];
      }
      if (!empty($emailAddr)) {
        $body[] = 'To update or cancel your booking request, please send an email with the relevant information to ' . $emailAddr;
      }
      $module = 'stanford_earth_r25';
      $key = 'r25_operation';
      $to = $mail_list;
      $params['message'] = $body;
      $params['r25_operation'] = $subject;
      $langcode = Drupal::currentUser()->getPreferredLangcode();
      $send = TRUE;
      $replyto = \Drupal::config('system.site')->get('mail');
      Drupal::service('plugin.manager.mail')->mail($module, $key, $to, $langcode, $params, $replyto, $send);
    }
    if (!empty($storage['room']['post_process_redirect_url']) && !empty($storage['room']['nopopup_reservation_form']) &&
      !empty($storage['event_state']) && $storage['event_state'] === StanfordEarthR25Util::STANFORD_R25_ROOM_STATUS_TENTATIVE &&
      !empty($form['#attached']['drupalSettings']['stanfordEarthR25']['pressRedirect']) &&
      $space_id === '2605') {
      $redirect = $storage['room']['post_process_redirect_url'];
      $startDate = '';
      $endDate = '';
      $dates = '';
      $email = '';
      $name = '';
      $startTime = '';
      $endTime = '';
      if (!empty($storage['mailto'])) {
        $email = $storage['mailto'];
      }
      if (!empty($storage['reserver_name'])) {
        $name = $storage['reserver_name'];
      }
      if (!empty($storage['dates']['start'])) {
        $temp = DrupalDateTime::createFromFormat(DATE_W3C, $storage['dates']['start']);
        $startDate = $temp->format('m/d/Y');
        $startTime = $temp->format('H:i');
      }
      if (!empty($storage['dates']['end'])) {
        $temp = DrupalDateTime::createFromFormat(DATE_W3C, $storage['dates']['end']);
        $endDate = $temp->format('m/d/Y');
        $endTime = $temp->format('H:i');
      }

      if (!empty($startDate)) {
        $dates = $startDate;
        if (!empty($endDate)) {
          $dates .= ' - ';
        }
      }
      $dates .= $endDate;
      $redirect = str_replace('[dates]', $dates, $redirect);
      $redirect = str_replace('[start]', $startTime, $redirect);
      $redirect = str_replace('[end]', $endTime, $redirect);
      $redirect = str_replace('[email]', $email, $redirect);
      $redirect = str_replace('[name]', $name, $redirect);
      $response = new TrustedRedirectResponse($redirect);
      $form_state->setResponse($response);
    }
  }
  $storage = $form_state->getStorage();
  unset($storage['stanford_earth_r25']['stanford_r25_postprocess']);
  $form_state->setStorage($storage);
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_stanford_r25_fullcalendar_limit_alter(&$calendar_limit) {
  if (!empty($calendar_limit['room']['rules_category'])) {
    if ($calendar_limit['room']['rules_category'] === 'hartley') {
      if (!empty(array_intersect(Drupal::currentUser()->getRoles(), ['custm_hartley_admin']))) {
        $calendar_limit['year'] = strval(date('Y') + 3);
      }
      else {
        $month = date('n');
        $year = date('Y');
        if ($month < 10) {
          $calendar_limit = array_merge($calendar_limit,
            ['month' => "12", 'day' => '31', 'year' => $year]);
        }
        else {
          $calendar_limit = array_merge($calendar_limit,
            ['month' => "12", 'day' => '31', 'year' => strval($year + 1)]);
        }
      }
    }
    elseif ($calendar_limit['room']['rules_category'] === 'press_building') {
      if (!empty(array_intersect(Drupal::currentUser()
        ->getRoles(), ['custm_press_building_user']))) {
        $calendar_limit = array_merge($calendar_limit,
          [
            'month' => date('n'),
            'day' => date('d'),
            'year' => strval(date('Y') + 1),
          ]);
      }
      elseif (!empty(array_intersect(Drupal::currentUser()
        ->getRoles(), ['custm_press_building_admin']))) {
        $calendar_limit = array_merge($calendar_limit,
          [
            'month' => date('n'),
            'day' => date('d'),
            'year' => strval(date('Y') + 3),
          ]);
      }
    }
  }
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_stanford_r25_isbillable_alter(&$is_billable) {
  $is_billable = FALSE;
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_stanford_r25_force_confirmed_alter(&$event_state, $booking_info) {
  $room_info = $booking_info['room'];
  if (!empty($room_info['rules_category']) && $room_info['rules_category'] === 'press_building') {
    if ($event_state === StanfordEarthR25Util::STANFORD_R25_ROOM_STATUS_TENTATIVE) {
      if ($booking_info['space_id'] != '2605') {
        if (!empty(array_intersect(
          Drupal::currentUser()->getRoles(), [
            'custm_press_building_user',
            'custm_press_building_admin',
          ]
        )
        )) {
          $event_state = StanfordEarthR25Util::STANFORD_R25_ROOM_STATUS_CONFIRMED;
        }
      }
    }
  }
}

/**
 * {@inheritdoc}
 */
function stanford_earth_hartley_stanford_earth_resform_title_alter(&$title, $location) {
  $category = $location->get('rules_category');
  if ($category === 'farm') {
    $title = "O'Donohue Family Farm Reservations";
  }
}
