<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\DrupalDateTime;

function stanford_earth_hartley_is_se3_user() {
  if (!empty(array_intersect(
    Drupal::currentUser()->getRoles(), ['custm_sdss_user','administrator']))) {
    return true;
  }
  return false;
}

function stanford_earth_hartley_is_hartley_room($form) {
  $is_hartley = false;
  if (!empty($form['stanford_r25_booking_roomid']['#value'])) {
    $roomid = $form['stanford_r25_booking_roomid']['#value'];
    if (is_string($roomid)) {
      $roomCode = substr($roomid, 0, 2);
      if ($roomCode === 'mh') {
        $is_hartley = true;
      }
    }
  }
  return $is_hartley;
}

function stanford_earth_hartley_is_farm_room($form) {
  $is_farm = false;
  if (!empty($form['stanford_r25_booking_roomid']['#value'])) {
    $roomid = $form['stanford_r25_booking_roomid']['#value'];
    if (is_string($roomid)) {
      $roomCode = substr($roomid, 0, 2);
      if ($roomCode === 'of') {
        $is_farm = true;
      }
    }
  }
  return $is_farm;
}

function stanford_earth_hartley_form_alter(&$form,
  \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'stanford_earth_r25_reservation') {
    // does the room use hartley rules?
    $hRules = (stanford_earth_hartley_is_hartley_room($form) ||
      stanford_earth_hartley_is_farm_room($form));
    if ($hRules) {
      if (empty($form['#validate'])) {
        $form['#validate'] = [];
      }
      $form['#validate'][] = 'stanford_earth_hartley_form_validate';
      if (empty($form['#submit'])) {
        $form['#submit'] = [];
      }
      $form['#submit'][] = 'stanford_earth_hartley_form_submit';
      $se3_user = stanford_earth_hartley_is_se3_user();

      $form['stanford_r25_booking_reason']['#title'] = 'Event name';

      $form['stanford_r25_booking_attr176']['#title'] = 'Is the event host using this space for the first time?';
      $form['stanford_r25_booking_attr176']['#description'] = 'If so, we will be in touch with additional instructions after your reservation is confirmed.';

      $form['stanford_r25_booking_attr169']['#title'] = 'Will food and/or beverages be served at this event?';
      $form['stanford_r25_booking_attr169']['#description'] = 'If so, you must acknowledge that a work order for cleanup ' .
        'is required and must be received by the Stanford Doerr School of Sustainability no less than 48 ' .
        'hours before the event.';
      $form['stanford_r25_booking_attr170']['#title'] = 'I agree to provide a work order for after-event cleanup.';
      $form['stanford_r25_booking_attr170']['#states'] = [
        'required' => [
          ':input[name="stanford_r25_booking_attr169"]' => [
            'checked' => true
          ],
        ],
        'visible' => [
          ':input[name="stanford_r25_booking_attr169"]' => [
            'checked' => true
          ],
        ]
      ];

      if ($roomCode === 'mh' && !empty(array_intersect(Drupal::currentUser()
          ->getRoles(), ['custm_hartley_administrator']))) {
        $form['stanford_r25_booking_attr171']['#type'] = 'hidden';
        $form['stanford_r25_booking_attr172']['#type'] = 'hidden';
        $form['stanford_r25_booking_attr173']['#type'] = 'hidden';
      }
      else {
        $form['stanford_r25_booking_attr171']['#type'] = 'markup';
        $form['stanford_r25_booking_attr171']['#markup'] = '<br/><strong>Please provide a PTA number and Sponsoring Department.</strong><br/>';
        $form['stanford_r25_booking_attr172']['#title'] = 'University PTA number';
        $form['stanford_r25_booking_attr172']['#description'] = 'PTA is required in format 1234567-1-ABCDE.';
        $form['stanford_r25_booking_attr172']['#required'] = true;
        /*
        $form['stanford_r25_booking_attr172']['#states'] = [
          'required' => [
            ':input[name="stanford_r25_booking_attr171"]' => [
              'checked' => TRUE
            ],
          ],
          'visible' => [
            ':input[name="stanford_r25_booking_attr171"]' => [
              'checked' => TRUE
            ],
          ],
        ];
        */
        $form['stanford_r25_booking_attr173']['#title'] = 'Sponsoring Department';
        $form['stanford_r25_booking_attr173']['#description'] = 'Which school department sponsors this PTA?';
        $form['stanford_r25_booking_attr173']['#required'] = true;
        /*
        $form['stanford_r25_booking_attr173']['#states'] = [
          'required' => [
            ':input[name="stanford_r25_booking_attr171"]' => [
              'checked' => TRUE
            ],
          ],
          'visible' => [
            ':input[name="stanford_r25_booking_attr171"]' => [
              'checked' => TRUE
            ],
          ],
        ];
        */
      }

      $form['stanford_r25_booking_attr177']['#title'] = 'Description/Comments';
      $form['stanford_r25_booking_attr177']['#description'] = 'Any information, questions or remarks about this reservation.';

      $form['stanford_r25_contact_175']['#title'] = 'Booking Contact Info';
      $form['stanford_r25_contact_175']['#required'] = TRUE;

    }
  }
}

function stanford_earth_hartley_form_validate(&$form, FormStateInterface $form_state) {
  if (!(Drupal::currentUser()->hasPermission('administer stanford r25') ||
    !empty(array_intersect(Drupal::currentUser()->getRoles(), ['custm_hartley_administrator'])))) {

    // Make sure there is a PTA number and sponsoring department.
    if (empty($form_state->getValue('stanford_r25_booking_attr172'))) {
      $form_state->setErrorByName('stanford_r25_booking_attr172',
        'Please provide a PTA number for billing for this reservation.');
      return;
    }
    else {
      // Check if the PTA number is in the correct format.
      $pta_str = $form_state->getValue('stanford_r25_booking_attr172');
      $results = [];
      $pattern = "/^[\d]{7,7}-[\d][\d\.]{0,7}-[A-Z]{5,5}$/";
      if (preg_match($pattern,$pta_str,$results) != 1) {
        $form_state->setErrorByName('stanford_r25_booking_attr172',
        'Please provide a PTA number in its proper format.');
        return;
      }
    }
    if (empty($form_state->getValue('stanford_r25_booking_attr173'))) {
      $form_state->setErrorByName('stanford_r25_booking_attr173',
        'Please provide a signature authority name for billing for this reservation.');
      return;
    }

    // Make sure the requested dates are in the accepted range.
    $month = intval(date('n'));
    $year = intval(date('Y'));
    $start_year = intval($form_state->getValue('stanford_r25_booking_date')->format('Y'));
    $end_year = intval($form_state->getValue('stanford_r25_booking_enddate')->format('Y'));
    if ($month < 10 && ($start_year != $year || $end_year != $year)) {
      $form_state->setErrorByName('stanford_r25_booking_date',
        'You may only reserve this space for dates during the current year.');
      return;
    }
    else {
      if ($start_year > $year + 1 || $end_year > $year + 1) {
        $form_state->setErrorByName('stanford_r25_booking_date',
          'You may only reserve this space for dates during the remainder of this year and next year.');
        return;
      }
    }
  }

  if (empty(trim($form_state->getValue('stanford_r25_contact_175')))) {
    $form_state->setErrorByName('stanford_r25_contact_175',
      'Please enter your contact information in the provided field.');
    return;
  }
  if (!empty($form_state->getValue('stanford_r25_booking_attr169')) &&
    intval($form_state->getValue('stanford_r25_booking_attr169')) == 1) {
    if (empty($form_state->getValue('stanford_r25_booking_attr170')) ||
      intval($form_state->getValue('stanford_r25_booking_attr170') == 0)) {
      $form_state->setErrorByName('stanford_r25_booking_attr170',
        'If you are serving food or beverages, you must agree to provide a work order for cleanup.');
      return;
    }
  }
}

function stanford_earth_hartley_form_submit(&$form, FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  if (!empty($storage['stanford_earth_r25']['stanford_r25_postprocess'])) {
    $storage = $storage['stanford_earth_r25']['stanford_r25_postprocess'];
    if (!empty($storage['mailto'])) {
      $room = $storage['room'];
      $dates = $storage['dates'];
      $mail_list = $storage['mailto'];

      $subject = $room['label'] . ': Your booking request is now pending approval';
      $body = [];
      $body[] = 'The Hartley booking manager will review and approve your request as soon as possible, and will contact you only if there is a problem.';
      $body[] = 'The details of your booking request follow.';
      $body[] = 'Event name: ' . $storage['event_name'];
      $space_str = 'Event space: ' . $room['label'];
      if ($room['id'] == 'mh01') {
        $space_str .= ' (Does *not* include Mitchell Patio)';
      }
      else {
        if ($room['id'] == 'mh02') {
          $space_str .= ' (Does *not* include Hartley Conference Room and Kitchen';
        }
      }
      $body[] = 'Event space: ' . $space_str;
      $body[] = 'Starting: ' . DateTime::createFromFormat(DATE_W3C, $dates['start'])
          ->format("l, F j, Y g:i a");
      $body[] = 'Ending: ' . DateTime::createFromFormat(DATE_W3C, $dates['end'])
          ->format("l, F j, Y g:i a");
      $est_fee = $storage['est_charge'];
      if ($est_fee > 0) {
        $body[] = 'Estimated Room Fee: $' . $est_fee . ' --reflects fee scheduled for time of event. Fees subject to change.';
      }
      $body[] = 'If food IS served or consumed, you must get a work order from Custodial Services. This is not negotiable. ';
      $body[] = 'Allow at least 30 minutes for cleanup if you get a work order.';
      $emailAddr = 'mailto:sdss-deans-office-reservations@stanford.edu';
      if (stanford_earth_hartley_is_farm_room($form)) {
        $emailAddr = 'mailto:jessgo@stanford.edu';
      }
      $body[] = 'To update or cancel your booking request, please send an email with the relevant information to ' . $emailAddr;
      $module = 'stanford_earth_r25';
      $key = 'r25_operation';
      $to = $mail_list;
      $params['message'] = $body;
      $params['r25_operation'] = $subject;
      $langcode = Drupal::currentUser()->getPreferredLangcode();
      $send = TRUE;
      $replyto = \Drupal::config('system.site')->get('mail');
      Drupal::service('plugin.manager.mail')->mail($module, $key, $to, $langcode, $params, $replyto, $send);
    }
  }
  $storage = $form_state->getStorage();
  unset($storage['stanford_earth_r25']['stanford_r25_postprocess']);
  $form_state->setStorage($storage);
}

function stanford_earth_hartley_stanford_r25_fullcalendar_limit_alter(&$calendar_limit) {
  if (!empty($calendar_limit['room']['id']) && substr($calendar_limit['room']['id'], 0, 3) == 'mh0') {
    if (Drupal::currentUser()->hasPermission('administer stanford r25') ||
      !empty(array_intersect(Drupal::currentUser()->getRoles(), ['custm_hartley_administrator']))) {
      $calendar_limit['year'] = strval(date('Y') + 3);
    }
    else {
      $month = date('n');
      $year = date('Y');
      if ($month < 10) {
        $calendar_limit = array_merge($calendar_limit,
          ['month' => "12", 'day' => '31', 'year' => $year]);
      }
      else {
        $calendar_limit = array_merge($calendar_limit,
          ['month' => "12", 'day' => '31', 'year' => strval($year + 1)]);
      }
    }
  }
}

function stanford_earth_hartley_stanford_r25_isbillable_alter(&$is_billable) {
  $is_billable = false;
  /*
  if ($is_billable) {
    $se3_user = stanford_earth_hartley_is_se3_user();
    if ($se3_user) {
      $is_billable = false;
    }
  }
  */
}
