<?php

namespace Drupal\stanford_earth_r25\Form;

use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\stanford_earth_r25\StanfordEarthR25Util;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\File\FileSystem;
use Drupal\stanford_earth_r25\Service\StanfordEarthR25Service;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 * Contains Drupal\stanford_earth_r25\Form\StanfordEarthR25CancelForm.
 */
class StanfordEarthR25CancelForm extends ConfirmFormBase {

  protected $location_id;

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'stanford_earth_r25_cancel';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $location_id = NULL, $event_id = NULL,
                            $start = NULL) {
    $storage = $form_state->getStorage();
    $result = $storage['stanford_earth_r25']['event_info'];
    $rooms = [];
    $room_id = $location_id;
    $this->location_id = $location_id;
    $adminSettings = [];
    if (!empty($room_id)) {
      $config = \Drupal::config('stanford_earth_r25.stanford_earth_r25.' . $room_id);
      $rooms[$room_id] = $config->getRawData();
      $config = \Drupal::config('stanford_earth_r25.adminsettings');
      $adminSettings = $config->getRawData();
    }

    // get the event title from the XML for display
    $title = '';
    if (!empty($result['vals'][$result['index']['R25:EVENT_NAME'][0]]['value'])) {
      $title = $result['vals'][$result['index']['R25:EVENT_NAME'][0]]['value'];
    }

    // find out if this is a recurring event so we can ask whether the operation
    // is for the instance or the entire series.
    $event_count = 0;
    if (!empty($result['index']['R25:RESERVATION_START_DT']) &&
      is_array($result['index']['R25:RESERVATION_START_DT'])
    ) {
      $event_count = count($result['index']['R25:RESERVATION_START_DT']);
    }

    $msg = 'Do you want to cancel reservation "';
    if (!empty($title)) {
      $msg .= Html::escape($title);
    }
    else {
      $msg .= $event_id;
    }
    $msg .= '"';
    if (!empty($rooms[$room_id]['display_name'])) {
      $msg .= ' in room ' . $rooms[$room_id]['display_name'];
    }
    if (!empty($start)) {
      $startdate = DrupalDateTime::createFromFormat(DATE_W3C, $start);
      $msg .= ' for ' . $startdate->format("l, F j, Y g:i a");
    }
    $msg .= '? <br />';
    $form['room_id'] = array(
      '#type' => 'hidden',
      '#value' => $room_id,
    );
    $form['event_id'] = array(
      '#type' => 'hidden',
      '#value' => $event_id,
    );
    $form['really'] = array(
      '#markup' => t($msg),
    );

    // if the event is part of a recurring series, display all the dates
    // and let user know confirmation applies to all instances in the series
    // or if operation is cancel, let them choose entire series or occurence.
    if ($event_count > 1) {
      $msg_text = 'This reservation is part of a series. Cancellation will apply to all dates.<br />';
      if (!empty($result['index']['R25:RESERVATION_START_DT']) &&
        is_array($result['index']['R25:RESERVATION_START_DT'])
      ) {
        $msg_text .= 'Reservation dates: <br/>';
        foreach ($result['index']['R25:RESERVATION_START_DT'] as $key => $value) {
          if (!empty($result['vals'][$value]['value'])) {
            $s_date = DrupalDateTime::createFromFormat(DATE_W3C, $result['vals'][$value]['value']);
            $msg_text .= $s_date->format("l, F j, Y g:i a") . '<br />';
          }
        }
        $msg_text .= '<br />';
      }
      $form['markup2'] = array(
        '#markup' => t($msg_text),
      );
      $form['series'] = array(
        '#type' => 'radios',
        '#default_value' => 1,
        '#options' => array(
          1 => 'Cancel this occurrence',
          2 => 'Cancel entire series'
        ),
      );
    }
    else {
      $form['series'] = array(
        '#type' => 'hidden',
        '#value' => 2,
      );
    }

    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $xyz = 1;
  }

  public function getConfirmText() {
    return $this->t('Cancel reservation');
    //return parent::getConfirmText(); // TODO: Change the autogenerated stub
  }

  public function getCancelText() {
    return $this->t('Return to calendar');
  }

  public function getQuestion() {
    return $this->t('Cancel Reservation?');
  }

  public function getCancelUrl() {
    return new Url('entity.stanford_earth_r25_location.calendar',['r25_location' => $this->location_id]);
  }

}

