<?php

/**
 * @file
 * Implements stanford_earth_r25 hooks for SE3-only customizations.
 */

/**
 * Implements hook_stanford_r25_contact_alter().
 */
function stanford_earth_r25_custom_stanford_r25_contact_alter(&$contactStr) {
  $users = \Drupal::entityTypeManager()->getStorage('user')
    ->loadByProperties(['name' => $contactStr]);
  if (!empty($users) && count($users) > 0) {
    foreach ($users as $user) {
      $displayName = $user->get('field_s_person_display_name')->getValue();
      if (!empty($displayName[0]['value'])) {
        $contactStr = $displayName[0]['value'];
      }
      break;
    }
  }
}
