<?php

/**
 * @file
 * Implements stanford_earth_r25 hooks for SE3-only customizations.
 */

/**
 * Implements hook_user_format_name_alter().
 */
function stanford_earth_r25_custom_user_format_name_alter(
  &$name,
  $account,
) {
  if (!empty($account)) {
    /** @var \Drupal\user\Entity\User $user */
    $user = \Drupal::entityTypeManager()->getStorage('user')
      ->load($account->id());
    if ($user) {
      $displayName = $user->get('field_su_display_name')->value;
      if (!empty($displayName)) {
        $name = $displayName;
      }
    }
  }
}
